In [1]:
import nltk

a='This is good movies. This is bad as that movie'
d={}

for token  in nltk.word_tokenize(a):
    if token not in d:
        d[token] = 1
    else :
        d[token]+=1

In [2]:
sentences = ['this is it it came all way',
            'he should have gone by this time',
            'is this really him talking',
             'i mad sure he tell lies',
             'something is strange']

In [3]:
sentences[0]

'this is it it came all way'

In [4]:
#we need unique words to define the length of vocabulary

unique_words = set()
for sent in sentences:
    for word in nltk.word_tokenize(sent):
        unique_words.add(word)

vocab={}

for i , word in enumerate(sorted(list(unique_words))):    
    vocab[word]=i
    

In [2]:
import pandas as pd
pd.__version__

'1.3.3'

In [5]:
vocab

{'all': 0,
 'by': 1,
 'came': 2,
 'gone': 3,
 'have': 4,
 'he': 5,
 'him': 6,
 'i': 7,
 'is': 8,
 'it': 9,
 'lies': 10,
 'mad': 11,
 'really': 12,
 'should': 13,
 'something': 14,
 'strange': 15,
 'sure': 16,
 'talking': 17,
 'tell': 18,
 'this': 19,
 'time': 20,
 'way': 21}

In [6]:
from collections import Counter
row=[]
col=[]
val=[]
for idx,sent in enumerate(sentences):
    count_vector=dict(Counter(sent.split(' ')))
    
    for word,count in count_vector.items():
    
        row.append(idx)
        col.append(vocab.get(word)) 
        val.append(count)

In [60]:
print(row)
print(col)
print(val)

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4]
[19, 8, 9, 2, 0, 21, 5, 13, 4, 3, 1, 19, 20, 8, 19, 12, 6, 17, 7, 11, 16, 5, 18, 10, 14, 8, 15]
[1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [70]:
print(csr_matrix((val,(row,col))).toarray())

[[1 0 1 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0]]


In [ ]:
#Diadvantage of COuntVetorizer
'''
*Its inability in identifying more important and less important words for analysis.
*It also doesn't identify the relationships between words such as linguistic similarity between words.
'''

In [7]:
#Using SKlearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer


In [8]:
documents=['Hi How are you','Hope you are doing good']

cv=CountVectorizer()
cv.fit(documents)
cv.get_feature_names()

['are', 'doing', 'good', 'hi', 'hope', 'how', 'you']

In [9]:
vector=cv.fit_transform(documents).toarray()
vector

array([[1, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 1]], dtype=int64)

In [84]:
import pandas as pd
pd.DataFrame(data=vector,columns=cv.get_feature_names())

are  doing  good  hi  hope  how  you
0    1      0     0   1     0    1    1
1    1      1     1   0     1    0    1

In [ ]:
#TFIDF

#What if we want words that are common but are not in abundant and not too rare,which shows the imporatnce of words
termfreq= frequency frqwuncy is the number of times the word i has occured in the document j to the total number of words in documents

log inverse= total number of documents to the documents that contain that word

TF-IDF is better than Count Vectorizers because it not only focuses on the frequency of words present
in the corpus but also provides the importance of the words.

In [139]:
documents=["The car is driven on the road","The truck is driven on the highway"]

In [140]:
tf=TfidfVectorizer()
tf.fit(documents)
tf.get_feature_names()

['car', 'driven', 'highway', 'is', 'on', 'road', 'the', 'truck']

In [141]:
tf.transform(documents).toarray()

array([[0.42471719, 0.30218978, 0.        , 0.30218978, 0.30218978,
        0.42471719, 0.60437955, 0.        ],
       [0.        , 0.30218978, 0.42471719, 0.30218978, 0.30218978,
        0.        , 0.60437955, 0.42471719]])

In [143]:
docA = "The car is driven on the road"

docB = "The truck is driven on the highway"

token_A = nltk.word_tokenize(docA)
token_B = nltk.word_tokenize(docB)

unique_words = set(token_A).union(set(token_B))
print(unique_words)

{'the', 'The', 'driven', 'car', 'is', 'road', 'on', 'highway', 'truck'}


In [144]:
def compute_TF(token_doc):
    
    bow_doc =dict(Counter(token_doc))
    print('bagOfWords--->', bow_doc)
    
    len_doc = len(token_doc)
    print('length of document-->',len_doc)
    
    tf_doc = { key : bow_doc[key]/len_doc for key in bow_doc.keys()}
    
    return tf_doc,bow_doc

In [145]:
TF_A , BOW_A = compute_TF(token_A)
TF_B , BOW_B= compute_TF(token_B)


print('TF_A---->',TF_A)
print('TF_B---->',TF_B)

bagOfWords---> {'The': 1, 'car': 1, 'is': 1, 'driven': 1, 'on': 1, 'the': 1, 'road': 1}
length of document--> 7
bagOfWords---> {'The': 1, 'truck': 1, 'is': 1, 'driven': 1, 'on': 1, 'the': 1, 'highway': 1}
length of document--> 7
TF_A----> {'The': 0.14285714285714285, 'car': 0.14285714285714285, 'is': 0.14285714285714285, 'driven': 0.14285714285714285, 'on': 0.14285714285714285, 'the': 0.14285714285714285, 'road': 0.14285714285714285}
TF_B----> {'The': 0.14285714285714285, 'truck': 0.14285714285714285, 'is': 0.14285714285714285, 'driven': 0.14285714285714285, 'on': 0.14285714285714285, 'the': 0.14285714285714285, 'highway': 0.14285714285714285}


In [146]:
def compuet_IDF(no_of_doc):
    import math
    total={}
    N=len(no_of_doc)
    for doc in no_of_doc:
        for key in doc.keys():
            if key in total:
                total[key]+=1
            else:
                total[key]=1
    print(total)
    for key, val in total.items():
        total[key] = math.log(N / float(val))
    
    
    return total

In [147]:
idf=compuet_IDF([BOW_A,BOW_B])
idf

{'The': 2, 'car': 1, 'is': 2, 'driven': 2, 'on': 2, 'the': 2, 'road': 1, 'truck': 1, 'highway': 1}


{'The': 0.0,
 'car': 0.6931471805599453,
 'is': 0.0,
 'driven': 0.0,
 'on': 0.0,
 'the': 0.0,
 'road': 0.6931471805599453,
 'truck': 0.6931471805599453,
 'highway': 0.6931471805599453}

In [148]:
def compute_TFIDF(TF_doc,idf):
    tfidf = {}
    for key, val in TF_doc.items():
        tfidf[key] = val * idf[key]
    return tfidf


In [149]:
tfidf_A=compute_TFIDF(TF_A,idf)
print(tfidf_A)
tfidf_B=compute_TFIDF(TF_B,idf)
print(tfidf_B)

import pandas as pd
df = pd.DataFrame([tfidf_A, tfidf_B])
df

{'The': 0.0, 'car': 0.09902102579427789, 'is': 0.0, 'driven': 0.0, 'on': 0.0, 'the': 0.0, 'road': 0.09902102579427789}
{'The': 0.0, 'truck': 0.09902102579427789, 'is': 0.0, 'driven': 0.0, 'on': 0.0, 'the': 0.0, 'highway': 0.09902102579427789}


The       car   is  driven   on  the      road     truck   highway
0  0.0  0.099021  0.0     0.0  0.0  0.0  0.099021       NaN       NaN
1  0.0       NaN  0.0     0.0  0.0  0.0       NaN  0.099021  0.099021

In [150]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform([docA,docB])
print(X.toarray())

[[0.42471719 0.30218978 0.         0.30218978 0.30218978 0.42471719
  0.60437955 0.        ]
 [0.         0.30218978 0.42471719 0.30218978 0.30218978 0.
  0.60437955 0.42471719]]
