In [2]:
import tensorflow

In [21]:
from tensorflow.keras.preprocessing.text import one_hot,Tokenizer

In [41]:
sentences= ['this glass of milk',
            'this milk glass is hot',
            'the fruit was not good',
            'He played excellent']

# One Hot Representation


In [42]:
one_hot_repr = [one_hot(word,100) for word in sentences]
one_hot_repr

[[90, 5, 91, 3], [90, 3, 5, 54, 39], [24, 30, 58, 19, 82], [53, 8, 66]]

In [ ]:
#pass this to embeddding layer to form matrix

In [43]:
token = Tokenizer(num_words=1000)
token.fit_on_texts(sentences)
token.word_index

token.texts_to_sequences(sentences)

[[1, 2, 4, 3], [1, 3, 2, 5, 6], [7, 8, 9, 10, 11], [12, 13, 14]]

In [44]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [17]:
import numpy as np

In [47]:
padded = pad_sequences(one_hot_repr,maxlen=5,padding = 'pre', truncating ='pre')

In [48]:
padded

array([[ 0, 90,  5, 91,  3],
       [90,  3,  5, 54, 39],
       [24, 30, 58, 19, 82],
       [ 0,  0, 53,  8, 66]])

In [50]:
model = Sequential()
model.add(Embedding(100,10,input_length  =5))
model.compile('adam','mse')

In [51]:
model.predict(padded)

array([[[ 0.00936234,  0.0361846 , -0.0392635 , -0.00846322,
          0.01530493,  0.02636017,  0.0167301 , -0.02215564,
          0.04939797, -0.01181148],
        [ 0.02700721,  0.01277884,  0.01312052, -0.02601175,
          0.04743867,  0.01997745,  0.00320622,  0.02168803,
         -0.01976942,  0.01323234],
        [ 0.00379182,  0.00060342,  0.0425001 , -0.01284522,
          0.03159039,  0.03298551,  0.01554097,  0.02418892,
          0.03036426,  0.04225177],
        [-0.02478694, -0.0340395 , -0.0097519 ,  0.03022095,
         -0.03805669, -0.03713442,  0.00328612, -0.03357768,
         -0.0234124 , -0.00320087],
        [-0.04386116,  0.0465299 ,  0.00624312,  0.01183497,
         -0.02848735, -0.01378923, -0.0136701 , -0.0007839 ,
          0.02696785, -0.00145662]],

       [[ 0.02700721,  0.01277884,  0.01312052, -0.02601175,
          0.04743867,  0.01997745,  0.00320622,  0.02168803,
         -0.01976942,  0.01323234],
        [-0.04386116,  0.0465299 ,  0.00624312,  0

In [53]:
padded[0]


array([ 0, 90,  5, 91,  3])

In [55]:
model.predict(padded)[0]

There were 4 sentences each word has its own vector dimension  of 10.

array([[ 0.00936234,  0.0361846 , -0.0392635 , -0.00846322,  0.01530493,
         0.02636017,  0.0167301 , -0.02215564,  0.04939797, -0.01181148],
       [ 0.02700721,  0.01277884,  0.01312052, -0.02601175,  0.04743867,
         0.01997745,  0.00320622,  0.02168803, -0.01976942,  0.01323234],
       [ 0.00379182,  0.00060342,  0.0425001 , -0.01284522,  0.03159039,
         0.03298551,  0.01554097,  0.02418892,  0.03036426,  0.04225177],
       [-0.02478694, -0.0340395 , -0.0097519 ,  0.03022095, -0.03805669,
        -0.03713442,  0.00328612, -0.03357768, -0.0234124 , -0.00320087],
       [-0.04386116,  0.0465299 ,  0.00624312,  0.01183497, -0.02848735,
        -0.01378923, -0.0136701 , -0.0007839 ,  0.02696785, -0.00145662]],
      dtype=float32)